[package]
name = "syntex_syntax"
version = "0.19.2"
authors = [ "erick.tryzelaar@gmail.com" ]
license = "MIT/Apache-2.0"
description = "Export of libsyntax for code generation"
repository = "https://github.com/erickt/rust-syntex"

[dependencies]
bitflags = "^0.3.2"
libc = "^0.1.10"
log = "^0.3.2"
rustc-serialize = "^0.3.16"
term = "^0.2.11"
unicode-xid = "^0.0.3"
